faiss_db:
  collection_name: "document_analysis"

embedding_model:
  provider: "google"
  model_name: "models/embedding-001"

retriver:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temprature: 0
    max_output_tokens: 2048
  
  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temprature: 0
    max_output_tokens: 2048